# Generated by Django 2.2.6 on 2019-10-20 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.CharField(max_length=10, verbose_name='Data de Criação')),
                ('descricao', models.CharField(max_length=300, verbose_name='Descrição')),
                ('vencimento', models.DateField(verbose_name='Vencimento')),
                ('quitado', models.BooleanField(verbose_name='Quitado')),
            ],
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pagamento', models.CharField(choices=[('Dinheiro', 'Dinheiro'), ('Cartão de Crédito', 'Cartão de Crédito'), ('Cartão de Débito', 'Cartão de Débito'), ('Cartão Crediário', 'Cartão Crediário'), ('Cheque', 'Cheque')], default='Dinheiro', max_length=20, verbose_name='Forma de Pagamento')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDespesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_despesa', models.CharField(choices=[('Remedio', 'Remedio'), ('Roupas', 'Roupas'), ('Alimentação', 'Alimentação'), ('Educação', 'Educação'), ('Transporte', 'Transporte'), ('Outros', 'Outros')], default='Alimentação', max_length=20, verbose_name='Tipo de Despesa')),
            ],
        ),
    ]
