# Generated by Django 2.2.6 on 2019-10-21 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DespesaAna', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoDespesa',
        ),
        migrations.RemoveField(
            model_name='formapagamento',
            name='forma_pagamento',
        ),
        migrations.AddField(
            model_name='despesa',
            name='forma_pagamento',
            field=models.CharField(choices=[('Dinheiro', 'Dinheiro'), ('Cartão de Crédito', 'Cartão de Crédito'), ('Cartão de Débito', 'Cartão de Débito'), ('Cartão Crediário', 'Cartão Crediário'), ('Cheque', 'Cheque')], default='Dinheiro', max_length=20, verbose_name='Forma de Pagamento'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='tipo_despesa',
            field=models.CharField(choices=[('Remedio', 'Remedio'), ('Roupas', 'Roupas'), ('Alimentação', 'Alimentação'), ('Educação', 'Educação'), ('Transporte', 'Transporte'), ('Outros', 'Outros')], default='Alimentação', max_length=20, verbose_name='Tipo de Despesa'),
        ),
    ]
