# Generated by Django 2.2.6 on 2019-10-21 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DespesaAna', '0002_auto_20191020_2107'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormaPagamento',
        ),
    ]
