# Generated by Django 2.2.6 on 2019-10-21 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DespesaAna', '0004_auto_20191020_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='data_criacao',
            field=models.DateField(verbose_name='Data de Criação'),
        ),
    ]
